# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: push 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run ESLint
      run: eslint '*/**/*.{js,ts,tsx}' --quiet